ci: use the releaseNotification step
elastic/apm-agent-ruby pull request #963
Opened 2021-02-11 18:14 UTC by v1v

### What

Use https://github.com/elastic/apm-pipeline-library/pull/976 to simplify the body manipulation
Enable email/slack communications when a tag release has created

### Issues

Need a the above-mentioned PR and also a release

2021-02-11 18:39 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-963/detail/PR-963/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-963/detail/PR-963/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-963/detail/PR-963/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-963/detail/PR-963/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-ruby_963.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #963 opened`



* Start Time: 2021-02-11T18:14:43.649+0000


* Duration: 24 min 13 sec


* Commit: c91cb06a9badd483cb1083be3fd4a8fd49986879



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 9  |
| Passed       | 51092  |
| Skipped      | 88 |
| Total        | 51189   |


#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-963/buildTimeGraph/png)


![Image of Tests](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-963/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![9](https://img.shields.io/badge/9%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-963/detail/PR-963/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-8-jdk#rails-6.0 / Rails integration transactions when there are ignored url patterns defined does not create events for the patterns – when there are ignored url patterns defined`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed Rails integration transactions when there are ignored url patterns defined does not create events for the patterns 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        execution expired
["./spec/support/mock_intake.rb:158:in `block in wait_for'", "./spec/support/mock_intake.rb:157:in `block in wait_for'", "./spec/support/mock_intake.rb:156:in `wait_for'", "./spec/integration/rails_spec.rb:253:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-8-jdk#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:222:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-8-jdk#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:242:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:jruby:9.2#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:222:in `block in <main>'", "/usr/local/bundle/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:jruby:9.2#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:242:in `block in <main>'", "/usr/local/bundle/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-11-jdk#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:222:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-11-jdk#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not th [...]

2021-02-16 08:25 UTC, mikker approved these changes
Taking into account that I know nothing about Jenkins, this LGTM 👍

2021-02-16 09:17 UTC, cachedout requested changes

2021-02-16 09:17 UTC, cachedout commented on .ci/Jenkinsfile
> +              notifyStatus(slackStatus: 'warning', subject: "[${env.REPO}] Release *${env.TAG_NAME}* got some syncup post-release failures.",
```suggestion
              notifyStatus(slackStatus: 'warning', subject: "[${env.REPO}] Release *${env.TAG_NAME}* has some sync-up post-release failures.",
```

2021-02-16 09:20 UTC, cachedout approved these changes

2021-02-16 12:36 UTC, merged