Fix GraphQL spec
elastic/apm-agent-ruby pull request #968
Opened 2021-02-17 08:36 UTC by mikker

2021-02-17 09:04 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-968/detail/PR-968/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-968/detail/PR-968/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-968/detail/PR-968/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-968/detail/PR-968/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-ruby_968.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #968 opened`



* Start Time: 2021-02-17T08:37:09.040+0000


* Duration: 27 min 34 sec


* Commit: f4ca0a6b7809f33fa3d0c43d6da675030fe3a244



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 7  |
| Passed       | 51281  |
| Skipped      | 93 |
| Total        | 51381   |


#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-968/buildTimeGraph/png)


![Image of Tests](https://apm-ci.elastic.co/job/apm-agent-ruby/job/apm-agent-ruby-mbp/job/PR-968/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![7](https://img.shields.io/badge/7%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-mbp%2FPR-968/detail/PR-968/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-8-jdk#rails-6.1 / Rails integration errors mailers when a mail is sent spans the mail – when a mail is sent`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed Rails integration errors mailers when a mail is sent spans the mail 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        execution expired
["./spec/support/mock_intake.rb:158:in `block in wait_for'", "./spec/support/mock_intake.rb:157:in `block in wait_for'", "./spec/support/mock_intake.rb:156:in `wait_for'", "./spec/integration/rails_spec.rb:350:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:jruby:9.2#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:216:in `block in <main>'", "/usr/local/bundle/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-13-jdk#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:216:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-11-jdk#rails-6.1 / GraphQL with multiple queries renames and concattenates – with multiple queries`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with multiple queries renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:216:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:jruby:9.2#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:236:in `block in <main>'", "/usr/local/bundle/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-13-jdk#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./spec/integration/graphql_spec.rb:236:in `block in <main>'", "/usr/local/bundle/jruby/2.5.0/gems/webmock-3.11.2/lib/webmock/rspec.rb:37:in `block in <main>'"]
       
 ```
</p></details>
</ul>
    
##### `Tests / Tests / Ruby:docker.elastic.co/observability-ci/jruby:9.2-11-jdk#rails-6.1 / GraphQL with too many queries to list renames and concattenates – with too many queries to list`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 failed GraphQL with too many queries to list renames and concattenates 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 
        
expected #<Integer:401> => 200
     got #<Integer:1001> => 500

Compared using equal?, which compares object identity,
but expected and actual are not the same object. Use
`expect(actual).to eq(expected)` if you don't care about
object identity in this example.


["./s [...]

2021-02-17 13:17 UTC, mikker commented on spec/integration/graphql_spec.rb
> +      # ActiveRecord::Base.logger = Logger.new(nil)
```suggestion
      ActiveRecord::Base.logger = Logger.new(nil)
```

2021-02-17 13:17 UTC, mikker commented on spec/integration/graphql_spec.rb
> +        #   )
```suggestion
        rescue StandardError => e
          logger.error e.message

          render(
            status: 500,
            json: { error: { message: e.message }, data: {} }
          )
```

2021-02-17 13:18 UTC, mikker commented on spec/integration/graphql_spec.rb
> +                  { query: q[:query], variables: q[:variables], context: context_.dup }
```suggestion
                  { query: q[:query], variables: q[:variables], context: context_ }
```

2021-02-17 14:10 UTC, estolfo commented
Copying what I wrote in slack: I don’t know where the source is exactly yet but it’s from this statement in the graphql spec: `Post.find_by(slug: slug)`. So I’m guessing it’s caused by a recent change between v6.1.1 and 6.1.2 to `ActiveRecord`. You could change it to `Post.where(slug: slug).first` and the test passes.

2021-02-17 15:13 UTC, estolfo requested changes

2021-02-17 15:13 UTC, estolfo commented on spec/integration/graphql_spec.rb
> +            Post.find_by(slug: slug).first
If you do `Post.where(slug: slug).first`, it will work

2021-02-18 09:18 UTC, estolfo approved these changes

2021-02-18 09:54 UTC, merged